name: schedule_management
description: A new Flutter project for managing schedules.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Updated minimum SDK constraint

dependencies:
  flutter:
    sdk: flutter

  # Other dependencies can be added here

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/Done.png
